name: Sync Fork
on:
  schedule:
    - cron: '*/5 * * * *' # Checks for upstream changes every 5 minutes
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} --branch main
